# Run this command to start the database:
# docker-compose up --build
version: "3"
services:
  db:
    hostname: 127.0.0.1
    image: pgvector/pgvector:pg16
    ports:
      - 5444:5444
    restart: always
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=erudites
      - POSTGRES_PASSWORD=erudites@123
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql