version: '3.9'

services:
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8090:8080"  # Map host 8090 to container 8080
    environment:
      ADMINER_DEFAULT_SERVER: sqlite
